### ISSUE TITLE
The classroom completion bar seems to be irrelevant to how many classes I marked as complete within that section

### ISSUE THREAD

**Issue by Mcoppola16x** [freshbrewedweb/wp-classroom#5]

**Comment by greghunt** [comment]
provide a screenshot example please. you should have checks beside the classes you've completed

**Comment by greghunt** [comment]
Do you mean _inaccurate_? Not irrelevant.

**Comment by Mcoppola16x** [comment]
Yes inaccurate - it seems like when I have zero check marks on classes that the percentages are up

**Comment by greghunt** [comment]
I can't replicate, can you show me?

It's accurate when I have classes completed. For example 2/12 = 17% completed under apprentice. Under mastery, I have 0 checks and it gives 0% completed.

**Comment by greghunt** [comment]
reopen if it's still an issue
