### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by Mcoppola16x** [freshbrewedweb/wp-classroom#6]
The avatars do not show up for anyone who doesn't have a gravatar or have it loaded in backend?

We should be able to allow students to add something simple (this will be crucial for classroom plugin perhaps no?)

**Comment by greghunt** [comment]
The plugin shouldn't really support front end user profiles. That's something particular to your website, if we can move this issue there, please.

Moved here: https://github.com/freshbrewedweb/superhero/issues/6
